"""add_user_context

Revision ID: d4ca20474b23
Revises: 
Create Date: 2025-08-19 13:59:28.279423

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'd4ca20474b23'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_contexts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('preferred_name', sa.String(), nullable=True),
    sa.Column('pronouns', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('tone_preference', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('dependents', sa.Integer(), nullable=True),
    sa.Column('income_band', sa.String(), nullable=True),
    sa.Column('rent_mortgage', sa.Float(), nullable=True),
    sa.Column('primary_financial_goal', sa.String(), nullable=True),
    sa.Column('subscription_tier', sa.String(), nullable=False),
    sa.Column('social_signals_consent', sa.Boolean(), nullable=False),
    sa.Column('ready_for_orchestrator', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('age_range', sa.String(), nullable=True),
    sa.Column('money_feelings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('housing_satisfaction', sa.String(), nullable=True),
    sa.Column('health_insurance', sa.String(), nullable=True),
    sa.Column('health_cost', sa.String(), nullable=True),
    sa.Column('learning_interests', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expenses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('identity', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('safety', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('style', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('location', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('locale_info', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('goals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('income', sa.String(), nullable=True),
    sa.Column('housing', sa.String(), nullable=True),
    sa.Column('tier', sa.String(), nullable=True),
    sa.Column('accessibility', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('budget_posture', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('household', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('assets_high_level', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('user_contexts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_contexts_email'), ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_contexts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_contexts_email'))

    op.drop_table('user_contexts')
    # ### end Alembic commands ###


